
spring:
  rabbitmq:
    # 发送确认
    publisher-confirm-type: correlated
    # 路由失败回调
    publisher-returns: true
    template:
      # 必须设置成true 消息路由失败通知监听者，false 将消息丢弃
      mandatory: true
    #消费端
    listener:
      simple:
        # 每次从RabbitMQ获取的消息数量
        prefetch: 1
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 1
        # 签收模式为手动签收-那么需要在代码中手动ACK
        acknowledge-mode: manual
  #消费者消费之后向生产者的反馈
  reply:
    queue:
      name: demo.reply-to
    exchange:
      name: demoReplyExchange
  sms:
    queue:
      name: demo.sms